//! Persistent prompt history stored as JSON in the OS app data dir.
//!
//! Each entry captures enough context to recall a past interaction without
//! having to keep the entire response on disk forever: the user prompt, the
//! first chunk of the response (as a preview), the provider / model and the
//! context that was attached. The full response is **not** persisted —
//! restoring an entry only re-fills the input; the user can re-send to
//! re-generate the full answer.
//!
//! The file is plain JSON and versioned. The store keeps the last
//! `MAX_ENTRIES` entries (FIFO eviction) so the file never grows without
//! bound.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use tauri::{AppHandle, Manager};
use thiserror::Error;

/// Bumped when the on-disk shape changes in a backwards-incompatible way.
pub const HISTORY_VERSION: u32 = 1;

/// Hard cap on the number of stored entries. Older entries are evicted on
/// insert so the on-disk file stays under ~1 MB even for power users.
pub const MAX_ENTRIES: usize = 200;

/// File name under `app_data_dir`.
const HISTORY_FILE: &str = "history.json";

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HistoryEntry {
    /// Stable identifier (uuid-ish string generated by the frontend).
    pub id: String,
    /// Unix timestamp in milliseconds.
    pub timestamp: i64,
    pub provider: String,
    pub model: String,
    pub prompt: String,
    /// Preview of the response, truncated on the backend to keep the file
    /// small. Used to render the list and to show on hover; the full
    /// response is not persisted.
    pub response_preview: String,
    pub context_preview: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PersistedHistory {
    #[serde(default = "default_version")]
    pub version: u32,
    #[serde(default)]
    pub entries: Vec<HistoryEntry>,
}

fn default_version() -> u32 {
    HISTORY_VERSION
}

#[derive(Debug, Error)]
pub enum HistoryStoreError {
    #[error("Could not resolve the application data directory")]
    MissingAppDir,
    #[error("I/O error: {0}")]
    Io(#[from] io::Error),
    #[error("Could not parse history: {0}")]
    Parse(#[from] serde_json::Error),
}

impl From<HistoryStoreError> for String {
    fn from(error: HistoryStoreError) -> Self {
        error.to_string()
    }
}

fn history_path(app: &AppHandle) -> Result<PathBuf, HistoryStoreError> {
    let resolver = app.path();
    let dir = resolver
        .app_data_dir()
        .map_err(|_| HistoryStoreError::MissingAppDir)?;
    Ok(dir.join(HISTORY_FILE))
}

fn ensure_parent(path: &Path) -> Result<(), HistoryStoreError> {
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() && !parent.exists() {
            fs::create_dir_all(parent)?;
        }
    }
    Ok(())
}

/// Maximum length of the response preview that is persisted per entry. Long
/// enough to be useful as a glance on the history panel, short enough to
/// keep the on-disk file small.
const RESPONSE_PREVIEW_CHARS: usize = 280;
const CONTEXT_PREVIEW_CHARS: usize = 160;

fn truncate_chars(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        return s.to_owned();
    }
    let mut out: String = s.chars().take(max).collect();
    out.push('…');
    out
}

fn now_millis() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

/// Reads the entire history. Returns an empty store if the file does not
/// exist yet (first run) or is corrupt (logged, treated as empty so the UI
/// can still render and the next save will overwrite the file with valid
/// JSON).
pub fn read_history(app: &AppHandle) -> Result<PersistedHistory, HistoryStoreError> {
    let path = history_path(app)?;
    if !path.exists() {
        return Ok(PersistedHistory::default());
    }
    let raw = fs::read_to_string(&path)?;
    if raw.trim().is_empty() {
        return Ok(PersistedHistory::default());
    }
    let value: Value = match serde_json::from_str(&raw) {
        Ok(value) => value,
        Err(error) => {
            tracing::warn!(
                %error,
                path = %path.display(),
                "history_store: ignoring malformed history file"
            );
            return Ok(PersistedHistory::default());
        }
    };
    let mut history: PersistedHistory = serde_json::from_value(value)?;
    history.version = HISTORY_VERSION;
    Ok(history)
}

/// Persists the history atomically (temp + rename).
pub fn write_history(
    app: &AppHandle,
    history: &PersistedHistory,
) -> Result<(), HistoryStoreError> {
    let path = history_path(app)?;
    ensure_parent(&path)?;
    let mut payload = history.clone();
    payload.version = HISTORY_VERSION;
    let json = serde_json::to_string_pretty(&payload)?;
    let tmp = path.with_extension("json.tmp");
    fs::write(&tmp, json.as_bytes())?;
    if path.exists() {
        fs::remove_file(&path)?;
    }
    fs::rename(&tmp, &path)?;
    Ok(())
}

/// Appends an entry to the history, evicting the oldest entries when the
/// cap is exceeded. The response and context are truncated to keep the
/// file size bounded.
pub fn append_entry(
    app: &AppHandle,
    raw_entry: HistoryEntry,
) -> Result<HistoryEntry, HistoryStoreError> {
    let mut history = read_history(app)?;
    let entry = HistoryEntry {
        response_preview: truncate_chars(&raw_entry.response_preview, RESPONSE_PREVIEW_CHARS),
        context_preview: raw_entry
            .context_preview
            .as_deref()
            .map(|c| truncate_chars(c, CONTEXT_PREVIEW_CHARS)),
        ..raw_entry
    };
    if entry.timestamp == 0 {
        // Defensive: if the frontend forgot to stamp the entry we still
        // want ordering to make sense.
        let mut stamped = entry;
        stamped.timestamp = now_millis();
        history.entries.push(stamped);
    } else {
        history.entries.push(entry);
    }
    if history.entries.len() > MAX_ENTRIES {
        let drop = history.entries.len() - MAX_ENTRIES;
        history.entries.drain(0..drop);
    }
    let stored = history.entries.last().cloned().unwrap();
    write_history(app, &history)?;
    Ok(stored)
}

/// Removes every entry from the history. Returns the count that was
/// removed so the UI can show a confirmation toast.
pub fn clear(app: &AppHandle) -> Result<usize, HistoryStoreError> {
    let mut history = read_history(app)?;
    let removed = history.entries.len();
    history.entries.clear();
    write_history(app, &history)?;
    Ok(removed)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample(id: &str, prompt: &str, response: &str) -> HistoryEntry {
        HistoryEntry {
            id: id.into(),
            timestamp: 1_700_000_000_000,
            provider: "ollama".into(),
            model: "llama3".into(),
            prompt: prompt.into(),
            response_preview: response.into(),
            context_preview: None,
        }
    }

    #[test]
    fn truncate_respects_character_boundaries() {
        let s = "áéíóú".repeat(100);
        let out = truncate_chars(&s, 10);
        // 10 visible chars + ellipsis.
        assert!(out.chars().count() <= 11);
        assert!(out.ends_with('…'));
    }

    #[test]
    fn truncate_returns_input_when_short_enough() {
        assert_eq!(truncate_chars("hello", 10), "hello");
    }

    #[test]
    fn serialised_shape_uses_camel_case() {
        let entry = sample("a", "p", "r");
        let json = serde_json::to_string(&entry).unwrap();
        assert!(json.contains("responsePreview"));
        assert!(!json.contains("response_preview"));
    }

    #[test]
    fn store_keeps_cap_invariant() {
        // The pure-data logic is exercised by the append_entry / write
        // functions when wired to a real AppHandle. Here we just assert the
        // constant and the FIFO semantics via the public surface.
        assert_eq!(MAX_ENTRIES, 200);
        let mut entries: Vec<HistoryEntry> = (0..MAX_ENTRIES + 5)
            .map(|i| sample(&format!("id-{i}"), "p", "r"))
            .collect();
        if entries.len() > MAX_ENTRIES {
            let drop = entries.len() - MAX_ENTRIES;
            entries.drain(0..drop);
        }
        assert_eq!(entries.len(), MAX_ENTRIES);
        assert_eq!(entries.first().unwrap().id, "id-5");
    }
}
